#!/bin/sh
#
# 50-kopano-config
#
# Functions defined in:
# docker-config.sh 10-kopano-common
#
#

#
# Configure Kopano if it is unlocked.
#
if dc_is_unlocked; then
	kopano_export_tls_cert
	kopano_generate_tls_cert
	kopano_export_tls_cert
	kopano_apply_envvars_core
	kopano_apply_envvars_webapp
	kopano_apply_envvars_zpush
	kopano_apply_envvar_propmap
fi
