#!/bin/bash
# hooks/build
# $DOCKER_REPO and $CACHE_TAG are injected into the build environment

echo "hooks/build called with IMAGE_NAME=${DOCKER_REPO}:${CACHE_TAG}, so we will run:"

case "${CACHE_TAG}" in
	"latest-core")          bld_target=kopano-core ;;
	"latest"|"latest-full") bld_target=kopano-full ;;
	"latest-debugtools")    bld_target=kopano-debugtools ;;
	"latest-webapp")        bld_target=kopano-webapp ;;
	*)
		echo "NOTHING since we do not know how to build with tag=${CACHE_TAG}"
		exit 1
	;;
esac

echo "docker build --target $bld_target -t ${DOCKER_REPO}:${CACHE_TAG} ."
docker build --target $bld_target -t ${DOCKER_REPO}:${CACHE_TAG} .
