#!/usr/bin/env bash
# hooks/post_push

version=$(src/docker/bin/kopano-webaddr.sh -VV)

_docker_add_tags() {
	local tag="$1"
	echo "hooks/post_push called with IMAGE_NAME=${DOCKER_REPO}:${DOCKER_TAG}, so we will use tag=$tag"
	docker tag $IMAGE_NAME $DOCKER_REPO:$tag
	docker push $DOCKER_REPO:$tag
}

if [[ "$DOCKER_TAG" == "full" ]]; then
	_docker_add_tags latest
	_docker_add_tags ${version}
	_docker_add_tags full-${version}
else
	_docker_add_tags ${DOCKER_TAG}-${version}
fi
