#!/bin/sh
#
# 50_update-loglevel
#
# If SYSLOG_LEVEL is not empty update syslog level
#

inform() { printf "entrypoint[$$]: INFO:$(basename $0): $*.\n" ;}

#
# run
#

if [ -n "$SYSLOG_LEVEL" ]; then
	inform "Setting syslogd level=$SYSLOG_LEVEL"
	setup-runit.sh "syslogd -nO- -l$SYSLOG_LEVEL $SYSLOG_OPTIONS"
fi
